#!/bin/bash

VALGRIND="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes"

for file in ./tests/*.oc; do
	echo -e "\nTESTS: running $file\n"
	 ./occ -vvpd --x86-long $file
	
#	echo -e "\nTESTS: V_WARN\n"
#	./occ --x86-long $file
#	./occ --x86-protected $file
#	./occ -p $file
#	./occ $file
#	
#	echo -e "\nTESTS: V_INFO\n"
#	./occ -v --x86-long $file
#	./occ -v --x86-protected $file
#	./occ -v -p $file
#	./occ -v $file
#	
#	echo -e "\nTESTS: with debug file\n"
#	./occ -d --x86-long $file
#	./occ -d --x86-protected $file
#	./occ -d -p $file
#	./occ -d $file
#	
#	echo -e "\nTESTS: V_DEBUG\n"
#	./occ -vv --x86-long $file 2> /dev/null
#	./occ -vv --x86-protected $file 2> /dev/null
#	./occ -vv -p $file 2> /dev/null
#	./occ -vv $file 2> /dev/null
#	
#	echo -e "\nTESTS: V_DEBUG and debug file\n"
#	./occ -vvd --x86-long $file 2> /dev/null
#	./occ -vvd --x86-protected $file 2> /dev/null
#	./occ -vvd -p $file 2> /dev/null
#	./occ -vvd $file 2> /dev/null
done
